### ISSUE TITLE
Store updates, but is not reflected in DOM

### ISSUE THREAD

**Issue by tarikhamilton** [Sambego/storybook-state#16]
I've tried both the StateDecorator method and State component.

Basically, I have an onChange handler in a component doing `store.set({ count: store.get('count') + 1 })`.

If I `console.log` `store.get('count')` inside the callback, I get the change. It'll continue to increment with each change.

But in my DOM, when I output the value, I get the initial state.

Here's a really simple example:

```
import React from "react";
import { storiesOf } from "@storybook/react";
import { StateDecorator, Store } from "@sambego/storybook-state";

const store = new Store({
  count: 0
});

storiesOf("storybook-state Test", module)
  .addDecorator(StateDecorator(store))
  .add("example", () => {
    return (
      <div>
        <p>Count: {store.get("count")}</p>
        <button
          onClick={() => {
            store.set({ count: store.get("count") + 1 });
            console.log("count", store.get("count"));
          }}
          value={store.get("count")}
        />
      </div>
    );
  });
```

If you can confirm this is a bug and not user error, I may be up for trying to fix it for Hacktoberfest.

**Comment by Sambego** [comment]
Hey @tarikhamilton, the `store.get()` method should only be used in callback functions and methods. It will not update the DOM. This is because React will only update the DOM if some properties of an element change. 

If you want to show data from the store you have 2 options. 

In most cases you will build your components to accept certain properties. The `<State />` element or state decorator will inject the attributes from the store as props into each element.

```
const CustomComponent = props => [
  <p>Count: {props.count}</p>,
  <button
    onClick={() => {
      store.set({ count: store.get("count") + 1 });
    }}
  >
    {props.count}
  </button>
];

storiesOf("storybook-state Test", module)
  .addDecorator(StateDecorator(store))
  .add("example", () => <CustomComponent />);
```

The `<State />` element and state decorator also accept a function instead of elements which will have the state as its first parameter.
```
storiesOf("storybook-state Test", module)
  .addDecorator(StateDecorator(store))
  .add("example", () => state => [
    <p>Count: {state.count}</p>,
    <button
      onClick={() => {
        store.set({ count: store.get("count") + 1 });
      }}
    >
      {state.count}
    </button>
  ]);
```

I hope this helps you!

If you feel like you can improve the docs to better reflect this, feel free to create a pull request. Improving documentation is also an important way of contributing to open source projects and count towards your Hacktoberfest goal :)

**Comment by tarikhamilton** [comment]
Ah. Thanks. I see it now in the docs... I'll think about the PR. I think emphasizing passing a function with `state` to the callback could be highlighted more, as I think that'll fit most people's use case.

**Comment by Sambego** [comment]
Feel free to open a new issue should you need some more explanation :)

**Comment by fabb** [comment]
Ah ok, when I use `addDecorator(withInfo)`, it works correctly (but depends on the order of the decorators). But when I use `.add("example", withInfo()(() => {...` it does not.

**Comment by dgana** [comment]
> Ah ok, when I use `addDecorator(withInfo)`, it works correctly (but depends on the order of the decorators). But when I use `.add("example", withInfo()(() => {...` it does not.

I still cannot get it to work to combine withInfo and stateDecorator. Can i see your code? Thanks

**Comment by fabb** [comment]
I gave up on making it work properly, I now have 2 stories of my component: one interactive without knobs and one non-interactive with knobs.

**Comment by dgana** [comment]
Ok thanks for the reply! @fabb
